export const PatientActions = {
    SET_PATIENT : 'SET_PATIENT',
    SET_PATIENT_PROFILE : 'SET_PATIENT_PROFILE',
    SET_BLOODPRESSURE : 'SET_BLOODPRESSURE',
    SET_DIABETES : 'SET_DIABETES',
    SET_MEDICINES : 'SET_MEDICINES',
    SET_PULSE : 'SET_PULSE',
    SET_CAL : 'SET_CAL',
    SET_COVID : 'SET_COVID',
    SET_COVID_TRACKER : 'SET_COVID_TRACKER',
    SET_READ : 'SET_READ'
   
}