export const DoctorActions = {
    SET_DOCTOR_PROFILE : 'SET_DOCTOR_PROFILE',
    SET_PATIENT_MONITOR : 'SET_PATIENT_MONITOR',
    SET_INVITATIONS : 'SET_INVITATIONS',
    REMOVE_INVITATION : 'REMOVE_INVITATION',
    SET_PRESCRIPTIONS : 'SET_PRESCRIPTIONS'
}